### ISSUE TITLE
Allow the customization of the tags displayed when hovering over the icon

### ISSUE THREAD

**Issue by Rings4** [doujincafe/doujincafe-discordbee#1]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2021-09-13 03 35 24 firefox](https://user-images.githubusercontent.com/32050292/133042735-c5ffff39-d48f-46f0-8971-52c4e8d74ad7.png)

The original discordbee allows you to display tags on hover over here. 
![Screenshot 2021-09-13 03 18 38 firefox](https://user-images.githubusercontent.com/32050292/133042280-31fb7f12-c174-4c18-86b4-c20b27c58fdd.png)

**Describe the solution you'd like**
I guess when the "Do not display file information" checkbox is checked, whatever is actually in the icon text area can be displayed instead.

**Comment by fumiichan** [comment]
Already on the latest branch. Will compile a new build tonight.
Commit: 91e4930

**Comment by fumiichan** [comment]
1.4.3 has been released. 🎉 
https://github.com/doujincafe/doujincafe-discordbee/releases/tag/1.4.3
